server.port=8080
spring.datasource.url=jdbc:mysql://mysql:vetapp.cv8mg4saihm7.ca-central-1.rds.amazonaws.com:3306/vetapp
spring.datasource.username=SLoS1245kIND
spring.datasource.password=SLoS1245kIND
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true