server.port=8080
spring.datasource.url=jdbc:mysql://mysqlsvc:3306/vetapp
spring.datasource.username=appuser
spring.datasource.password=iims
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true