apiVersion: v1
kind: ConfigMap
metadata:
  name: appconfigmap
  namespace: application
data:
  MYSQL_DATABASE: "vetapp"
  MYSQL_USER: "appuser"

---
apiVersion: v1
kind: Secret
metadata:
  name: appsecret
  namespace: application
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "cm9vdDEyMw==" #root123
  MYSQL_PASSWORD: "aWltcw==" #iims

