apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: servicemonitor
  namespace: monitoring
  labels:
    relase: stable
spec:
  selector:
    matchLabels:
      stack: monitoring 
  namespaceSelector:
    matchNames:
      - application
  endpoints:
    - port: mon
      path: "/actuator/prometheus"
      interval: "15s"    
