apiVersion: apps/v1
kind: Deployment
metadata:
  name: apppod
  namespace: application
spec:
  replicas: 1
  selector:
    matchLabels:
      city: pune
  template:    
    metadata:
      labels:
        city: pune
    spec:
      containers:
        - name: mycon
          image: sw1236/springboot-kubernetes-project:94
