apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: application
spec:
  replicas: 1
  selector:
    matchLabels:
      name: app
  template:
    metadata:
      labels:
        name: app
    spec:
      containers:
         - name: con1
<<<<<<< HEAD
           image: sw1236/springboot-kubernetes-project:55
=======
           image: sw1236/springboot-kubernetes-project:55
>>>>>>> d4e602d6d6cbcd75932dfde07bb0650f91fccb1e
