apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-deployment
  namespace: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      name: testEnv-Pod
      labels:
        app: test
    spec:
      containers:
        - name: container
          image: sw1236/springboot-kubernetes-project_v4:v4