apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: spring-boot-monitor
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: application

  namespaceSelector:
    matchNames:
      - application

  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s

---

apiVersion: v1
kind: Service
metadata:
  name: application-service
  namespace: application
  labels:
    app: monitoring
spec:
  selector:
    app: application
  ports:
    - name: http
      port: 8080
      targetPort: 8080