name: ci/cd
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: vetapp
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:
      - name: copy code
        uses: actions/checkout@v4

      - name: setup java
        uses: actions/setup-java@v5
        with:
          java-version: '8'
          destribution: 'tumrin'

      - name: build jar
        run: mvn clean install 

      - name: upload artifact
        uses: actions/upload-artifact@v4
