name: ci/cd
on:
  push:
    branches:
      - main

jobs:
  build:
    run-on: ubuntu:latest
    steps:
      - name: copy code
        use: actions/checkout@v4
      - name: setup java
        use: actions/setup-java@v4
      - name: build jar
        run: mvn clean install
        with:
          java-version: '8'
          destribution: 'tumrin'
      - name: upload artifact
        use: actions/upload-artifact@v4
